### ISSUE TITLE
fix: icon font file is not loading

### ISSUE THREAD

**Issue by rickalday** [impress-org/give-simple-social-shout#10]
Social icones are not loading.

There's an error in the console:
Failed to load resource: the server responded with a status of 403 (Forbidden)
https://s3.amazonaws.com/icomoon.io/114779/Socicon/style.css

Related tickets:
https://secure.helpscout.net/conversation/1155500789/64552?folderId=672194

**Comment by mathetos** [comment]
Ug... I knew I shouldn't have relied on them. 

Probably going to swap this out for SVGs.
